"""Free, in-process signals about how an image was produced.

None of these are conclusive on their own, but together they are a cheap first
line of defence before (or instead of) a paid AI-image detector:

- Camera EXIF (Make/Model/exposure) is a *positive* signal of a real photo.
- Generator fingerprints in metadata (software tags, C2PA/SynthID markers,
  AI tool names) are a *negative* signal.

Everything here is best-effort: metadata is trivially strippable, so absence of
camera EXIF is weak evidence, while a generator fingerprint is stronger.
"""

import base64
import binascii
import io
from typing import List

from PIL import ExifTags, Image

# Substrings that genuinely indicate AI-generated imagery. Two kinds only:
#   1. Specific generator/tool names unlikely to occur in a real photo's metadata.
#   2. Explicit AI-provenance assertions / watermarks.
# Deliberately NOT here: ambiguous common words that are carried by real, edited,
# or stock images too. "c2pa" is the biggest trap — Content Credentials are a
# provenance standard used by cameras (Leica/Nikon/Sony) and Photoshop/Lightroom,
# not an AI marker; only its `trained algorithmic media` digitalSourceType asserts
# AI. Likewise "gemini" (zodiac/app brands), "leonardo" (da Vinci), "firefly"
# (the insect / apps), "imagen" (Spanish "image"), "flux" (magnetic flux/CSS), and
# "openai" (appears in unrelated captions) cause false positives, so they're out.
_GENERATOR_FINGERPRINTS = (
    # 1. Specific generator/tool names
    "midjourney", "dall-e", "dall·e", "stable diffusion", "stablediffusion",
    "sdxl", "automatic1111", "comfyui", "adobe firefly", "leonardo.ai",
    "nightcafe", "novelai",
    # 2. Explicit AI provenance assertions / watermarks
    "synthid", "trained algorithmic media", "ai-generated", "generated by",
)

_CAMERA_EXIF_TAGS = {"Make", "Model", "DateTimeOriginal", "ExposureTime", "FNumber", "ISOSpeedRatings", "LensModel"}


def _decode(image_base64: str) -> bytes:
    raw = image_base64.split(",", 1)[-1].strip()
    return base64.b64decode(raw + "==", validate=False)


def inspect_metadata(image_base64: str) -> dict:
    """Return cheap provenance signals extracted from the image bytes.

    Shape:
      {
        "has_camera_exif": bool,
        "camera": "<Make Model>" | None,
        "generator_fingerprints": [str],   # matched AI/editor markers
        "ai_metadata_suspected": bool,
      }
    """
    result = {
        "has_camera_exif": False,
        "camera": None,
        "generator_fingerprints": [],
        "ai_metadata_suspected": False,
    }

    try:
        data = _decode(image_base64)
    except (binascii.Error, ValueError):
        return result

    haystacks: List[str] = []
    try:
        img = Image.open(io.BytesIO(data))
        exif = img.getexif()
        if exif:
            named = {ExifTags.TAGS.get(k, str(k)): v for k, v in exif.items()}
            present = _CAMERA_EXIF_TAGS.intersection(named.keys())
            if present:
                result["has_camera_exif"] = True
                make = str(named.get("Make", "")).strip()
                model = str(named.get("Model", "")).strip()
                cam = f"{make} {model}".strip()
                result["camera"] = cam or None
            haystacks.extend(str(v) for v in named.values())
        # PNG/text metadata + any format info dict.
        haystacks.extend(str(v) for v in getattr(img, "info", {}).values())
    except Exception:  # noqa: BLE001 - unreadable metadata is just a weak signal
        pass

    # Also scan a slice of the raw bytes for embedded XMP/C2PA strings.
    try:
        haystacks.append(data[:4096].decode("latin-1", errors="ignore"))
        haystacks.append(data[-2048:].decode("latin-1", errors="ignore"))
    except Exception:  # noqa: BLE001
        pass

    blob = " ".join(haystacks).lower()
    matched = sorted({fp for fp in _GENERATOR_FINGERPRINTS if fp in blob})
    result["generator_fingerprints"] = matched
    result["ai_metadata_suspected"] = bool(matched)
    return result
